### ISSUE TITLE
[Android] Support for Instagram share

### ISSUE THREAD

**Issue by levsthings** [react-native-community/react-native-share#117]
As of right now, I can't find any packages that support sharing to Instagram out of the box. ```react-native-share``` seems to be one of the most complete sharing packages around and I think implementing Instagram would be great. I see that there was a [PR](https://github.com/EstebanFuentealba/react-native-share/pull/34) for this but didn't get much attention and didn't get merged for some reason. Maybe @EstebanFuentealba can elaborate why. 

Is anyone interested in working towards adding Instagram share?

**Comment by superandrew213** [comment]
@levsthings I made that PR a long time ago and since then `react-native-share` code has changed. I don't have time to update my PR for it work with the current version of `react-native-share`.

My [fork](https://github.com/superandrew213/react-native-share) works perfectly fine for sharing files (especially for Instagram) so feel free to use it. I use it in a production app so will maintain and keep it up to date.

**Comment by ershubhamgarg** [comment]
@levsthings @superandrew213 @heracek  Can you please tell me how do I share the image on Instagram through iOS platform ?

**Comment by superandrew213** [comment]
@filipef101 the `custom` branch should work:
https://github.com/superandrew213/react-native-share/tree/custom

**Comment by MateusAndrade** [comment]
Closing this issue, since you can actually share on Instagram with the current release.
