### ISSUE TITLE
title option not working

### ISSUE THREAD

**Issue by nblumoe** [react-native-community/react-native-share#178]
The option `title` in the following call does not have any apparent effect:

```js
Share.open({
          url: `data:application/pdf;base64,${response.data}`,
          title: "my title",
        })
```

The share dialog on Android still will have the title "Share". Is the option broken?

**Comment by ataillefer** [comment]
Yes, it seems it's broken since 3466bbc.
Look at the following diffs:

- "title" option taken into account:
https://github.com/EstebanFuentealba/react-native-share/commit/3466bbc#diff-f8f2fa183a121e3e22f46f4a5ceef3ebL99

- hardcoded title:
https://github.com/EstebanFuentealba/react-native-share/commit/3466bbc#diff-3fda3b361cc3bfe1acf44b82a68acc9dR24

Maybe @EstebanFuentealba  can do something about it or you can submit a PR for this one?

**Comment by nblumoe** [comment]
@ataillefer thanks for investigating this and finding the issue!
I consider doing a PR for this but as this isn't high on my priority list, I don't want to raise expectations of handing this in too soon.

**Comment by yeomann** [comment]
Hi there, closing issues, as it seems to be fixed. Please feel free to open it again thanks 😃

**Comment by MuhammadMattiullah** [comment]
@yeomann its still not working. I am adding a title key in the share options object but it's not appearing as a title in IOS and Android.

const shareUrl = `${config.shareUrl}/conversations/${conversation.id}`;
const title = conversation.subject || conversation.body.slice(0, 60);
    const shareOptions = {
      title: title,
      url: shareUrl,
    };
    Share.open(shareOptions);
But when i pass message and url it concatenate the message and url as a title.
But i want to show only the title.
How can i say this? @nblumoe
