### ISSUE TITLE
Allow param on `open` function to determine whether to reject if user cancels share

### ISSUE THREAD

**Issue by sam1463** [react-native-community/react-native-share#245]
Feature request:

Currently, the `open` method rejects if the user clicks "cancel" in the share menu. Would it be possible/desirable to pass an optional param to not reject on user cancel? Something like this:

```
Share.open({
... options,
failOnCancel: false, // would default to true, since that's current behavior
}).catch((err) => {
handleError(err); // we'd no longer get the "User did not share" error here since failOnCancel = false
});
```

Happy to look into it and if successful, submit a PR, just wanted to know if that's something people are interested/ok with adding.

**Comment by fawcilize** [comment]
The culprit: https://github.com/react-native-community/react-native-share/blob/54f195857975b1a9c0cef46c786583c10f611e8f/index.js#L45

Right now it appears the "User did not share message" is the only way to determine if a request is cancelled, so changing this string is a breaking change since consumers will be checking for it specifically in catch blocks. It should probably be put into a const to make that clear.

**Comment by sam1463** [comment]
That's true, however, allowing an additional option to be passed in would not be a breaking change if the default value for the additional option results in the behavior that users currently experience.
