### ISSUE TITLE
Multiple share in iOS

### ISSUE THREAD

**Issue by NawazKhanMd** [react-native-community/react-native-share#340]
i have tried multiple share in android its working fine,
when i tried to do it in iOS with changed path 

> var path = RNFS.DocumentDirectoryPath + '/' + trimmedFileName;
file is successfully written.
so when I try to share with code 
`let shareOptions = {
            type: "application/pdf",
            title: "Share Via",
            message: message,
            urls: dataArray,
        };
        Share.open(shareOptions);`

dataArray holds the urls to downloaded file in array

when i select a medium such as mail only message is viewed and i cant see the files listed in the attachments

but single sharing is working with the code 
`let shareOptions = {
            type: "application/pdf",
            title: "Share Via",
            message: message,
            url: dataArray[0],
        };
        Share.open(shareOptions);
`

**Comment by NawazKhanMd** [comment]
@jgcmarins  What information u might need ? :(

**Comment by atull** [comment]
@NawazKhanMd This working fine on my end. I am testing the on iPhone5s & I am able to see all the attachments in my mail while trying to share them.

Can you also once check by adding few Https image urls in the array & then try to share, see if its working in your project. This can give a more clarity, if the problem is in library or the path document you are trying to share.

**Comment by atull** [comment]
@NawazKhanMd @yeomann You could try something like below shared code:

const shareOptions = {
        title: 'Share via',
        urls: ['https://img.icons8.com/search/2266EE', 'https://img.icons8.com/color/search'],
    };
    Share.open(shareOptions);

I guess, if this works then the issue is not related to library. The issue could be with one of the URI's of the documents, although i'm not sure of it. @NawazKhanMd Can you also cross check with all the document's paths you are receiving in dataArray in your example?

**Comment by nicubarbaros** [comment]
@atull Nope, this doesnot work. The dialog it's opening but It cant seem to find any app to be shared on.

**Comment by jgcmarins** [comment]
@NawazKhanMd did you solve?

**Comment by NawazKhanMd** [comment]
Yes i did solved using version 1.0.27
