### ISSUE TITLE
Release only crash

### ISSUE THREAD

**Issue by keshamtravels** [react-native-community/react-native-share#402]
It is working totally fine in development build .It ia all working when i even do react-native run-android --variant=release but the app crashes only in release builds

**Comment by mikehardy** [comment]
Please provide versions of everything, a crash stack trace, and ideally a link to your github repo so we can reproduce it

**Comment by mikehardy** [comment]
crash traces are still useful - if you say it crashes, seeing the line in react-native-share where it crashes (or the stack trace that leads to it) would be useful. But I also see that you aren't on the current version of react-native-share so I'm not sure how to support it

I will say - maybe totally unrelated - that crashes between dev and release for me were typically caused by bundling errors where differences between the metro bundler and webpack were exposed. There was a big problem with that if you moved gradle from 3.1.x to 3.2.x https://github.com/facebook/react-native/issues/18357 if you don't have react-native 0.57.2 (I think?) or higher because gradle changed asset locations.

There's no reason in general that there should be a difference in behavior with react-native-share between dev and prod though

**Comment by henkkasoft** [comment]
I just noticed the same behaviour. Also very urgent problem for me. Released to TestFlight and all the sudden share is not working.

I will look this more on tomorrow but I noticed that when sharing Whatsapp and Facebook Messenger the share component crash. Sharing with text message or email is not crashing (some proplems with them also but not sure they are related to this).

And everything was working fine when testing with debug-build with xcode and test-device.

**Comment by keshamtravels** [comment]
sorry for late reply, @mikehardy  i am unable to get stack trace because it is correctly working in development build and release build when run through --variant=release but it only crashes when installed through apk

**Comment by jgcmarins** [comment]
@keshamtravels could you try running with [logcat](https://developer.android.com/studio/command-line/logcat)?
`adb logcat`

**Comment by loubacking** [comment]
Same case, please if you get a resolution for this, share here 👍

**Comment by henkkasoft** [comment]
@loubacking I did find one solution that fixed the problem for me, but it doesn't explain any core reason.
I also use react-native-image-crop-picker in my project and there is an new issue with resizing to given width and height in iOS (I am resizing to 1024x1024).
https://github.com/ivpusic/react-native-image-crop-picker/issues/843

So I added back @leomercier suggestion there and also the share started to work again. So you might want to check if pictures with resolution 1024x1024 are working with you?

**Comment by keshamtravels** [comment]
Well i installed the newest version of rect-native share 
then a problem of cl.json occured which i solved using

https://github.com/react-native-community/react-native-share/issues/200#issuecomment-361938532

![image](https://user-images.githubusercontent.com/37133281/49813426-6e724a00-fd8d-11e8-87ea-6aac613f2778.png)

ant then it worked
