### ISSUE TITLE
Compile release apk not work

### ISSUE THREAD

**Issue by crsgarcias** [react-native-community/react-native-share#415]
### Steps to reproduce
1. cd android
2. gradlew assembleRelease
3. (To work, I had to **update my gradle**)
 * android/app/build.graddle
compileSdkVersion 28
targetSdkVersion 28
implementation "com.android.support:appcompat-v7:28.0.0"

* android/build.properties
classpath 'com.android.tools.build:gradle:3.2.1'

* android/gradle/gradle-wrapper.properties
distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-all.zip

### Expected behaviour
Compile and install APK on Android to work

### Actual behaviour
**Compile without error but when I installed in Android not works**
**Note: In emulator Its work**
The last log is:
?[9A?[1m<?[0;32;1;0;39;1m-------------> 0% WAITING?[m?[26D?[1B> IDLE?[6D?[1B> IDLE?[6D?[1B> IDLE?[0K?[6D?[1B> IDLE?[6D?[1B> IDLE?[6D?[1B?[1m> :react-native-smart-
splashscreen:mergeReleaseResources?[m?[56D?[1B> IDLE?[6D?[1B> IDLE?[6D?[1B?[9A?[2K?[1B?[2K?[1B?[2K?[1B?[2K?[1B?[2K?[1B?[2K?[1B?[2K?[1B?[2K?[1B?[2K?[8AC

### Environment
- **React Native version**: 0.54
- **React Native platform + platform version**: iOS 9.0, Android 5.0, etc, Android 8

### react-native-share
**Version**: npm version or "master"

### Link to repo (highly encouraged)
https://github.com/

**Comment by mikehardy** [comment]
With gradle >= 3.2 and React Native < 0.57.2 you need a workaround to put the bundle in the right place for releases on Android.

https://github.com/react-native-community/react-native-share/issues/386#issuecomment-432232419

Can you confirm you have done this? Otherwise the Android Java code misses the handoff to the Javascript

**Comment by crsgarcias** [comment]
Thank you, I can´t reach compile my app

**Comment by crsgarcias** [comment]
I added the script in package.json, but not works, I had the same result

**Comment by mikehardy** [comment]
@crsgarcias there is not information in your comment to provide any help, sorry

Perhaps you could record your terminal session (https://asciinema.org/) starting from the point where you npm install and continuing until your issue?

**Comment by crsgarcias** [comment]
Ok thank you, I had to update my react native to 0.57.7. And the error was fixed. Thank you!

**Comment by mikehardy** [comment]
Yes! Great news, and yes - react-native > 0.57.2 works well with modern gradles. Good  luck

**Comment by SarfarazAhmedKhan** [comment]
i am facing an issue of release which i solved after days 2 hard working and search answer every where but no positive result...
the problem was that i am trying to make release APK after making a whole project which results me in case of not running on mobile the release apk i am trying to run on other mobiles results in fails...
after that i start a new project and step by step after each iterations or changing in code i make and upgrade that APK by using gradlew assembleReference which results me in success...
