### ISSUE TITLE
providing image path, but im only getting the path

### ISSUE THREAD

**Issue by A7madXatab** [react-native-community/react-native-share#500]
## Ask your Question

I am providing this file from device to the share, I should be getting the image but instead, I'm getting the file path as a text, this is the code, I am providing the 'file://' extension too.

the imagePath= /data/user/0/com.bashi/cache/react-native-img-cache/64dfe4328de3ca110d4182a882a60a0a78d91b17.jpeg
`  const imagePath = RNFetchBlob.fs.dirs.CacheDir + "/react-native-img-cache/" + this.state.imagePathOnDevice;
    Share.open({
      url: imagePath,
    });
`

expected behavior: receiving the image I want to share
but I'm getting the path as a text

**Comment by MateusAndrade** [comment]
> but I'm getting the path as a text

Hi @A7madXatab . You can please fill the issue template?

Also, im sharing a image on the device using this approach:

```javascript
  const shareInfo = {
    title,
    url: image, //relative path to the image.
    subject,
  };

 ShareCustom.open(shareInfo);
```

Hope it helps!

**Comment by xliank** [comment]
You shouldn't have read file directly from application path or manual create a path link because it's hard to debug. If you really need to read file storage, I would recommend try https://github.com/itinance/react-native-fs. 

I would recommend you return as base64 from RNFetchblob before share it .
Here is my link how to  https://github.com/react-native-community/react-native-share/issues/533#issuecomment-508459727
