### ISSUE TITLE
Possible Unhandled Promise Rejection (id: 0): TypeError: Cannot read property 'showShareActionSheetWithOptions' of undefined

### ISSUE THREAD

**Issue by Luckygirlllll** [react-native-community/react-native-share#721]
### Steps to reproduce
1. const shareOptions = {
            title: 'Share via',
            message: 'some message',
            url: "https://civicchamps.com",
        };
        console.log("new code")
        Share.open(shareOptions)
2. Getting an error in IOS when trying to share:" Possible Unhandled Promise Rejection (id: 0): TypeError: Cannot read property 'showShareActionSheetWithOptions' of undefined"
3.

### Expected behaviour
Can share 

### Actual behaviour
Getting an error

### Environment
- **React Native version**: 0.59.1
- **React Native platform + platform version**: iOS 13

### react-native-share
**Version**: npm version or "master" 1.2.1

### Link to repo (highly encouraged)
https://github.com/

**Comment by MateusAndrade** [comment]
Are you using the [v1.2.1](https://github.com/react-native-community/react-native-share/tree/v1.2.1)? We got a lot of changes since v1.2.1, that can fix that.  

You can give a look at the complete changelog here: https://github.com/react-native-community/react-native-share/compare/v1.2.1...v3.0.0. 

Also, did you tried updating your app to a newer version of `react-native`? On this case, this can have some benefits since you are going from 0.59.1 to 0.60.
