### ISSUE TITLE
Share.open(email addressee) does not work on iOS

### ISSUE THREAD

**Issue by WQvist** [react-native-community/react-native-share#763]
### Steps to reproduce
1. Add email addressee in share options
2. Share via mail
3. Recipient is empty

### Expected behaviour
Recipient in mail app should be email given in options

### Actual behaviour
Recipient is empty

### Environment
- **React Native version**: 0.61.5
- **React Native platform + platform version**: iOS 12.4.4

### react-native-share
**Version**: npm version ^3.0.0

**Comment by MateusAndrade** [comment]
Hi @WQvist, which app you are trying to share? The default mail on iOS?

Possibly related to #414.

**Comment by WQvist** [comment]
Yes, the default mail app on iOS.
Looks to be related. But I ended up using another library (which I can't remember the name of in the moment.)

**Comment by MateusAndrade** [comment]
> Looks to be related. But I ended up using another library (which I can't remember the name of in the moment.)

Could you share that? Maybe this can help other people facing this issue. 😄

**Comment by WQvist** [comment]
I don't have access to the work repo at home, but I can write a comment and close the issue on thursday when I'm back at work.

**Comment by WQvist** [comment]
I used https://github.com/chirag04/react-native-mail to share with the iOS mail app.

**Comment by martinzhang777** [comment]
> I don't have access to the work repo at home, but I can write a comment and close the issue on thursday when I'm back at work.

Hello, the email address still can't be brought in automatically

**Comment by Sachin-kulal** [comment]
Hello,
On Android, the recipient email address is correctly populated when sharing via email, but on iOS, the recipient field remains empty. This issue persists even after updating to the latest react-native-share version (12.0.9).

Steps to Reproduce:

Add an email address in the share options.
Share via the Mail app on iOS.
Expected Behavior:
The recipient field in the Mail app should be pre-filled with the provided email address.

Actual Behavior:
The recipient field is empty in the Mail app on iOS.

Environment:

React Native version: 0.70.0
Platform + version: iOS 12.4.4
react-native-share version: 10.2.1 (also tested on 12.0.9)
Note:
The functionality works correctly on Android but fails on iOS.
