### ISSUE TITLE
Share.Social.MESSENGER - undefined

### ISSUE THREAD

**Issue by vinikatyal** [react-native-community/react-native-share#782]
## Ask your Question

```
      const shareOptions = {
        title: 'Share via',
        message: `${message} ${item.link}`,
        social: Share.Social[appId],
        url: uri,
        whatsAppNumber: '',
      };
      if (
        appId === 'FACEBOOK' ||
        appId === 'INSTAGRAM' ||
        appId === 'WHATSAPP' ||
        appId === 'MESSENGER'
      ) {
        Share.shareSingle(shareOptions);
      } else {
        Share.open(shareOptions);
      }
```

When I try to share single through messenger it gives me an error :

`Object {
  "error": "key 'social' missing in options",
}
`

However i am providing the Social id above.

Share.Social.MESSENGER shows as **undefined**

![Screenshot 2020-05-21 at 1 47 19 PM](https://user-images.githubusercontent.com/5568656/82538658-b17f4200-9b69-11ea-805e-a84f45d60d0f.png)

**Comment by Graig123git** [comment]
+1

**Comment by thilinawarnakula** [comment]
@vinikatyal  Any solutions?

**Comment by vinikatyal** [comment]
@MateusAndrade Would you know about this?

**Comment by MateusAndrade** [comment]
> @MateusAndrade Would you know about this?

Sorry for the long time to answer. 😅 

Looking at the example you provided, are you trying to use this `appId` as the same values exported by rn-share. If this is right, unfortunately right now we don't support `messenger` as a target on iOS using `Share.single`. 

You can look at the implementation here: https://github.com/react-native-community/react-native-share/blob/10c72e4a6a54042fc98c16d69a773fad4034b246/ios/RNShare.m#L107-L161

However, on Android this will work since the `single` method only calls the native API. 

https://github.com/react-native-community/react-native-share/blob/10c72e4a6a54042fc98c16d69a773fad4034b246/android/src/main/java/cl/json/RNShareModule.java#L147-L170

There is anything that I can help you @vinikatyal, @thilinawarnakula, @Graig123git?

**Comment by davidwinograd1** [comment]
any updates?
